-- Database Schema for Ekeson Group Gadget Store

-- 1. Profiles table (extends Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'customer' CHECK (role IN ('admin', 'customer')),
  needs_password_reset BOOLEAN DEFAULT true,
  secret_answer TEXT DEFAULT 'Udi',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(12, 2) NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('phones', 'laptops', 'pads', 'accessories', 'gadgets', 'smart_watches', 'earbuds')),
  condition TEXT DEFAULT 'new' CHECK (condition IN ('new', 'uk-used')),
  brand TEXT,
  image_url TEXT,
  inventory INTEGER DEFAULT 0,
  status TEXT DEFAULT 'In Stock' CHECK (status IN ('In Stock', 'Out of Stock', 'Restocking Soon')),
  is_featured BOOLEAN DEFAULT false,
  specs JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Orders table
CREATE TABLE orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  total_amount DECIMAL(12, 2) NOT NULL,
  status TEXT DEFAULT 'processing' CHECK (status IN ('processing', 'shipped', 'delivered', 'cancelled')),
  payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed')),
  shipping_address TEXT,
  contact_phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Order Items table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price DECIMAL(12, 2) NOT NULL
);

-- 5. Settings table (Global App Configuration)
CREATE TABLE settings (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1), -- Single row table
  usdt_wallet_address TEXT,
  usdt_network TEXT DEFAULT 'TRC20',
  shipping_fee_inside_lagos_abuja DECIMAL(12, 2) DEFAULT 0.00,
  shipping_fee_outside_lagos_abuja DECIMAL(12, 2) DEFAULT 0.00,
  shipping_fee_african_countries DECIMAL(12, 2) DEFAULT 0.00,
  paystack_public_key TEXT,
  flutterwave_public_key TEXT,
  monnify_api_key TEXT,
  monnify_contract_code TEXT,
  bank_transfer_details TEXT,
  opay_merchant_id TEXT,
  palmpay_merchant_id TEXT,
  warranty_policy_text TEXT DEFAULT 'This is the default warranty policy. It can be changed in the admin dashboard.',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Messages table (Customer Care Chat)
CREATE TABLE messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id TEXT NOT NULL, -- To group chats for non-logged in users by cookie/session
  sender TEXT NOT NULL CHECK (sender IN ('user', 'admin')),
  text TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Contact Submissions table (Support and Contact forms)
CREATE TABLE contact_submissions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'unread' CHECK (status IN ('unread', 'read', 'resolved')),
  type TEXT DEFAULT 'contact' CHECK (type IN ('contact', 'support')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Policies for Products
CREATE POLICY "Products are viewable by everyone." ON products FOR SELECT USING (true);
CREATE POLICY "Only admins can modify products." ON products FOR ALL 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Policies for Orders
CREATE POLICY "Users can view their own orders." ON orders FOR SELECT 
  USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Users can insert their own orders." ON orders FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Policies for Order Items
CREATE POLICY "Users can view their own order items." ON order_items FOR SELECT 
  USING (EXISTS (SELECT 1 FROM orders WHERE orders.id = order_id AND (orders.user_id = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))));

-- Policies for Settings
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Settings viewable by everyone." ON settings FOR SELECT USING (true);
CREATE POLICY "Only admins can modify settings." ON settings FOR ALL 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Policies for Messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can insert messages." ON messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view all messages." ON messages FOR SELECT 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
-- Users view their own messages (frontend checks session_id)
CREATE POLICY "Users can view their own session messages." ON messages FOR SELECT 
  USING (session_id = current_setting('request.jwt.claims', true)::jsonb->>'session_id' OR true); -- Permissive select, frontend filters by session id.

-- Policies for Contact Submissions
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can insert contact submissions." ON contact_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Only admins can view and modify contact submissions." ON contact_submissions FOR ALL 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Function to get order status safely (bypasses RLS)
CREATE OR REPLACE FUNCTION public.get_order_status(p_order_id UUID)
RETURNS jsonb AS $$
DECLARE
  v_order jsonb;
BEGIN
  SELECT jsonb_build_object(
    'id', id,
    'status', status,
    'payment_status', payment_status,
    'created_at', created_at
  ) INTO v_order
  FROM public.orders
  WHERE id = p_order_id;
  
  RETURN v_order;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user profile
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Seed some initial data
INSERT INTO products (name, description, price, category, condition, brand, image_url, inventory, status, is_featured)
VALUES 
('MacBook Pro M3', '14-inch, M3 chip, 8GB RAM, 512GB SSD', 2450000, 'laptops', 'new', 'Apple', 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80', 10, 'In Stock', true),
('iPhone 15 Pro Max', '256GB, Titanium Blue', 1850000, 'phones', 'new', 'Apple', 'https://images.unsplash.com/photo-1696446701796-da61225697cc?w=800&q=80', 15, 'In Stock', true),
('iPad Pro 12.9', 'M2 chip, 128GB, Space Gray', 1250000, 'pads', 'new', 'Apple', 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80', 5, 'In Stock', true),
('Sony WH-1000XM5', 'Industry Leading Noise Cancelling Headphones', 450000, 'gadgets', 'new', 'Sony', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80', 20, 'In Stock', true);

INSERT INTO settings (id, usdt_wallet_address, usdt_network, shipping_fee_inside_lagos_abuja, shipping_fee_outside_lagos_abuja, shipping_fee_african_countries, warranty_policy_text)
VALUES (1, 'TYP89...YourWalletAddress', 'TRC20', 3500.00, 7500.00, 25000.00, 'Our premium items come with a standard 1-Year warranty directly from our global partners. For more details, please contact technical support.');
