-- Database Schema for Ekeson Group Gadget Store

-- 1. Profiles table (extends Supabase Auth)
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  role TEXT DEFAULT 'customer' CHECK (role IN ('admin', 'customer')),
  needs_password_reset BOOLEAN DEFAULT true,
  secret_answer TEXT DEFAULT 'Udi',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Products table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(12, 2) NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('phones', 'laptops', 'pads', 'accessories', 'gadgets', 'smart_watches', 'earbuds')),
  condition TEXT DEFAULT 'new' CHECK (condition IN ('new', 'uk-used')),
  brand TEXT,
  image_url TEXT,
  inventory INTEGER DEFAULT 0,
  status TEXT DEFAULT 'In Stock' CHECK (status IN ('In Stock', 'Out of Stock', 'Restocking Soon')),
  is_featured BOOLEAN DEFAULT false,
  specs JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Orders table
CREATE TABLE orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  total_amount DECIMAL(12, 2) NOT NULL,
  status TEXT DEFAULT 'processing' CHECK (status IN ('processing', 'shipped', 'delivered', 'cancelled')),
  payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed')),
  shipping_address TEXT,
  contact_phone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Order Items table
CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price DECIMAL(12, 2) NOT NULL
);

-- 5. Settings table (Global App Configuration)
CREATE TABLE settings (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1), -- Single row table
  usdt_wallet_address TEXT,
  usdt_network TEXT DEFAULT 'TRC20',
  shipping_fee_inside_lagos_abuja DECIMAL(12, 2) DEFAULT 0.00,
  shipping_fee_outside_lagos_abuja DECIMAL(12, 2) DEFAULT 0.00,
  usdt_rate DECIMAL(12, 2),
  shipping_fee_african_countries DECIMAL(12, 2) DEFAULT 0.00,
  paystack_public_key TEXT,
  flutterwave_public_key TEXT,
  monnify_api_key TEXT,
  monnify_contract_code TEXT,
  bank_transfer_details TEXT,
  opay_merchant_id TEXT,
  palmpay_merchant_id TEXT,
  warranty_policy_text TEXT DEFAULT 'This is the default warranty policy. It can be changed in the admin dashboard.',
  delivery_policy_text TEXT DEFAULT 'This is the default delivery & shipping policy. It can be changed in the admin dashboard.',
  privacy_policy_text TEXT DEFAULT 'This is the default privacy policy. It can be changed in the admin dashboard.',
  refund_policy_text TEXT DEFAULT 'This is the default refund & returns policy. It can be changed in the admin dashboard.',
  terms_policy_text TEXT DEFAULT 'This is the default terms and conditions. It can be changed in the admin dashboard.',
  is_maintenance_mode BOOLEAN DEFAULT false,
  is_checkout_locked BOOLEAN DEFAULT false,
  footer_hq_address TEXT DEFAULT 'Lagos/Abuja Nigeria',
  footer_hq_phone TEXT DEFAULT '+234 814 852 7697',
  footer_hq_email TEXT DEFAULT 'office@ekesongroup.com',
  footer_service_links JSONB DEFAULT '[{"label":"Order Tracking","url":"/track-order"},{"label":"Technical Support","url":"/support"},{"label":"Warranty Policy","url":"/warranty"},{"label":"Contact Office","url":"/contact"}]'::jsonb,
  footer_policy_links JSONB DEFAULT '[{"label":"Delivery/Shipping Policy","url":"/delivery-shipping"},{"label":"Terms and Conditions","url":"/terms"},{"label":"Privacy Policy","url":"/privacy"},{"label":"Refund Policy","url":"/refund"}]'::jsonb,
  header_links JSONB DEFAULT '[{"label":"Phones","url":"/category/phones"},{"label":"Laptops","url":"/category/laptops"},{"label":"Pads","url":"/category/pads"},{"label":"Accessories","url":"/category/accessories"},{"label":"PlayStation","url":"/category/playstation"},{"label":"Drones","url":"/category/drones"}]'::jsonb,
  hero_title TEXT DEFAULT 'PREMIUM TECH<br/>SIMPLE ACCESS',
  hero_subtitle TEXT DEFAULT 'Nigeria''s most trusted destination for genuine brand new and Grade-A UK used gadgets. Verified standards, transparent pricing.',
  hero_media_url TEXT,
  hero_media_type TEXT DEFAULT 'image',
  footer_brand_text TEXT DEFAULT 'Nigeria''s trusted source for premium global technology. Professional service, verified specifications, and secure logistics.',
  footer_catalog_links JSONB DEFAULT '[{"label":"Smartphones","url":"/category/phones"},{"label":"Laptops","url":"/category/laptops"},{"label":"Tablets & Pads","url":"/category/pads"},{"label":"Accessories","url":"/category/accessories"}]'::jsonb,
  live_chat_script TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Blocked Customers table (Restricts abusive users by phone number)
CREATE TABLE blocked_customers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  phone TEXT UNIQUE NOT NULL,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Messages table (Customer Care Chat)
CREATE TABLE messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id TEXT NOT NULL, -- To group chats for non-logged in users by cookie/session
  sender TEXT NOT NULL CHECK (sender IN ('user', 'admin')),
  text TEXT NOT NULL,
  is_read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Contact Submissions table (Support and Contact forms)
CREATE TABLE contact_submissions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'unread' CHECK (status IN ('unread', 'read', 'resolved')),
  type TEXT DEFAULT 'contact' CHECK (type IN ('contact', 'support')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Reviews table
CREATE TABLE reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Set up Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Policies for Products
CREATE POLICY "Products are viewable by everyone." ON products FOR SELECT USING (true);
CREATE POLICY "Only admins can modify products." ON products FOR ALL 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Policies for Orders
CREATE POLICY "Users can view their own orders." ON orders FOR SELECT 
  USING (auth.uid() = user_id OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Users can insert their own orders." ON orders FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "Admins can update orders." ON orders FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Policies for Order Items
CREATE POLICY "Users can view their own order items." ON order_items FOR SELECT 
  USING (EXISTS (SELECT 1 FROM orders WHERE orders.id = order_id AND (orders.user_id = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))));

-- Policies for Settings
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Settings viewable by everyone." ON settings FOR SELECT USING (true);
CREATE POLICY "Only admins can modify settings." ON settings FOR ALL 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Policies for Reviews
CREATE POLICY "Approved reviews viewable by everyone." ON reviews FOR SELECT USING (status = 'approved' OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Users can insert their own reviews." ON reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Only admins can modify reviews." ON reviews FOR UPDATE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Only admins can delete reviews." ON reviews FOR DELETE USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Policies for Messages
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can insert messages." ON messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view all messages." ON messages FOR SELECT 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
-- Users view their own messages (frontend checks session_id)
CREATE POLICY "Users can view their own session messages." ON messages FOR SELECT 
  USING (session_id = current_setting('request.jwt.claims', true)::jsonb->>'session_id' OR true); -- Permissive select, frontend filters by session id.

-- Policies for Contact Submissions
ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can insert contact submissions." ON contact_submissions FOR INSERT WITH CHECK (true);
CREATE POLICY "Only admins can view and modify contact submissions." ON contact_submissions FOR ALL 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Function to get order status safely (bypasses RLS)
CREATE OR REPLACE FUNCTION public.get_order_status(p_order_id UUID)
RETURNS jsonb AS $$
DECLARE
  v_order jsonb;
BEGIN
  SELECT jsonb_build_object(
    'id', id,
    'status', status,
    'payment_status', payment_status,
    'created_at', created_at
  ) INTO v_order
  FROM public.orders
  WHERE id = p_order_id;
  
  RETURN v_order;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user profile
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Seed some initial data
-- (Dummy products removed for live production)

INSERT INTO settings (id, usdt_wallet_address, usdt_network, shipping_fee_inside_lagos_abuja, shipping_fee_outside_lagos_abuja, shipping_fee_african_countries, warranty_policy_text)
VALUES (1, 'TYP89...YourWalletAddress', 'TRC20', 3500.00, 7500.00, 25000.00, 'Our premium items come with a standard 1-Year warranty directly from our global partners. For more details, please contact technical support.');
